data={
"category" :   "(For ST,SC,General Category) (Fresh)",
"subcategory" :    "Postmatric Other Than Intermediate (Fresh)",
"district" :   "MEERUT",
"districtIndx" :   1,
"institute" :      "MEERUT INSTITUTE OF ENGINEERING & TECHNOLOGY, MEERUT - 250005 ",
"instituteIndx" :   1,
"caste" :      "सामान्य वर्ग",
"casteIndx" :      1,
"religion" :      "HINDU",
"religionIndx" :      1,
"studentName":     "Student Name",
"fatherName":     "Father Name",
"motherName":     "Mother Name",
"dob":     "12/09/2000",
"gender":     "FEMALE",
"female":      "FEMALE",
"nameChanged":     1,
"newName":     "New Name",
"highSchoolPassingYear":       2017,
"highSchoolBoard":       'CBSE',
"hsbIndx":     1,
"highSchoolAlphaRoll":   "A"  ,
"highSchoolRoll":      53456845,
"highSchoolName":      "Hgh School Name",
"highSchoolAddress":      "Hgh School Address",
"tele":    0,
"mobile":      9123456780,
"email":       "fakemail@gmail.com" ,
"password":    "Pass@123"
}
